### ISSUE TITLE
Intrinsic format?

### ISSUE THREAD

**Issue by antithing** [cvg/GeoCalib#3]
Hi, and thanks for making this code available.
What format are intrinsics calculated in? Fx, fy, cx,cy and distortion?

Thanks!

**Comment by sarlinpe** [comment]
https://github.com/cvg/GeoCalib/blob/917ebb94543aa25291a07d768566a86ff2d38614/geocalib/camera.py#L27-L31

The principal point is not estimated and instead assumed to be at the center of the image, but this can be overwritten if different. The distortion parameters depend on the selected camera model.

**Comment by antithing** [comment]
Thanks! Is there a way to calculate the principal point as well?

Does camera_model="simple_radial" give a 5 parameter  matrix for distortion?

**Comment by sarlinpe** [comment]
> Is there a way to calculate the principal point as well?

We always assume that the principal point is at the center of the image but it should be possible to set a different value if needed:
https://github.com/cvg/GeoCalib/blob/89182c053841d6463efda6c93e5b8532d519624e/geocalib/lm_optimizer.py#L46-L49
https://github.com/cvg/GeoCalib/blob/917ebb94543aa25291a07d768566a86ff2d38614/geocalib/camera.py#L58
We haven't tried to optimize the principal point and I would bet that it is currently not sufficiently constrained.

> Does camera_model="simple_radial" give a 5 parameter matrix for distortion?

https://github.com/cvg/GeoCalib/blob/917ebb94543aa25291a07d768566a86ff2d38614/geocalib/camera.py#L542-L546

**Comment by veichta** [comment]
It seems that the model is not moved to the GPU. Make sure that you are also moving the model to the correct device:

> model = GeoCalib(weights="distorted")

should be 

`model = GeoCalib(weights="distorted").to(device)`

**Comment by antithing** [comment]
That was it. Thank you!
