### ISSUE TITLE
cannot open laval dataset website

### ISSUE THREAD

**Issue by JizheXIA** [cvg/GeoCalib#4]
Cannot open http://hdrdb.com/indoor/#presentation/. It seems something is wrong with the website.
Do you have any other way to download the dataset? 

Thanks for reply

**Comment by sarlinpe** [comment]
Thank you for reporting this issue. I suggest reaching out to Jean-François Lalonde over email: https://iid.ulaval.ca/equipes/jean-francois-lalonde/ We do not have the right to distribute the dataset ourself.

**Comment by sarlinpe** [comment]
It looks like the dataset is back online, closing this.

**Comment by miangoleh** [comment]
its offline again! Did you end up sending the email?
