### ISSUE TITLE
Multiple frame optimization

### ISSUE THREAD

**Issue by Yasaman-Haghighi** [cvg/GeoCalib#5]
Hello,

Thank you for your great work! Is there a script available for optimizing camera parameters using multiple images captured from the same camera?

Thanks in advance!

**Comment by sarlinpe** [comment]
You can pass a batch of images: `model.calibrate(image_batch, shared_intrinsics=True)`
https://github.com/cvg/GeoCalib/blob/dd26a4e8bde5ac59b7aa4d9f6111fbc0dc484eb0/geocalib/extractor.py#L66-L72
We should indeed document this, sorry that it isn’t right now.

**Comment by Yasaman-Haghighi** [comment]
Thanks a lot for your quick reply!

**Comment by alhojel** [comment]
Does this work with other camera models other than pinhole? Can we just average the intrinsic matrix?

**Comment by veichta** [comment]
At the moment, it only works for pinhole cameras. If you want to use it for other camera models, you would have to adapt the [calculations in the optimizer](https://github.com/cvg/GeoCalib/blob/1d2d1740372d8b8e05a69c99c67f204481b086c9/siclib/models/optimization/lm_optimizer.py#L243C13-L264C20), which should be doable. 
Simply averaging does work but is not as effective as the joint optimization as show in Figure 8 of the paper.

**Comment by maro-bearrobotics** [comment]
calibrate function does not support a list of image tensors.

code 
```
batch = []
for filename in os.listdir(image_dir):
    if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif', '.tiff')):
        image_path = os.path.join(image_dir, filename)
        image = model.load_image(image_path).to(device)  # RGB로 통일
        batch.append(image)


# image = model.load_image("path/to/image.jpg").to(device)
result = model.calibrate(batch, shared_intrinsics=True)

print("camera:", result["camera"])
print("gravity:", result["gravity"])
```

```
  File "/home/maro_jeon/Works/GeoCalib/geocalib/extractor.py", line 92, in calibrate
    if len(img.shape) == 3:
AttributeError: 'list' object has no attribute 'shape'
```

How does it support multiple images ?
